apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
spec:
  replicas: 3  # Nombre de réplicas souhaité
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: victormarti/cluster:flask_1.0
        ports:
        - containerPort: 5000
        env:
        - name: DB_HOST
          value: "postgres-svc"
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: "requestdb"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  selector:
    app: webapp
  ports:
  - port: 80
    targetPort: 5000
  type: NodePort  # Ou LoadBalancer selon votre infrastructure